### ISSUE TITLE
2020-03-13

### ISSUE THREAD

**Issue by OysterQAQ** [cheer-fun/pixivic-pc#1]
* 友情链接 bug
* 详情页去掉懒加载并且居中
* 图片404给标示
* 搜索推荐标签没有
* 点击Pixivic回到首页瀑布流不变(应当变成排行的)
* 排行选择器换一个图标 换成时钟

**Comment by OysterQAQ** [comment]
右上角两个没用的图标先隐藏

**Comment by hyperMoss** [comment]
友情链接 bug fixd
详情页去掉懒加载并且居中 fixd
图片404给标示 fixd
搜索推荐标签没有 ？文档无
点击Pixivic回到首页瀑布流不变(应当变成排行的) fixd
排行选择器换一个图标 换成时钟 fixd
