### ISSUE TITLE
pc端初步测试

### ISSUE THREAD

**Issue by goblinM** [cheer-fun/pixivic-pc#2]
pixivic PC端正式问题
1.	用户中心登录后，样式变形。建议用户中心后期优化，可设头像，可改名称。
2.	排行搜索妹子图片很可爱，但是太隐蔽了，不移动到图片上不知道还有这个排行功能。
 3.	尚未完成的功能？消息，个人中心，推荐画师，我的收藏点击都无效。
4.	搜索排行中的综合排行，女性，男性画作为空应该显示没有内容，然后不断在这两个切换的话偶尔会出现这个情况。
5.	搜索排行中比如切到综合排行默认选择日为单位，切到漫画排行的时候也应该默认设置日为单位，不要默认为空，不然整个页面还是处于综合排行的页面。
6.	顶部的快速搜索中，切换漫画，插画，作者没有效果。
7.	收藏图片失败，接口报错。
8.	搜索作品输入为空时，页面一片空白，可以设置默认展示图片
9.	画作详情页面中画师其他的画作以及头像展示问题
10.	画师添加关注失败
11.	详细大图加载太慢了。
12.	详情页建议可以切换上下小图片，不需要默认大图才可以切换。
13.	如果重复点击了某个路由，控制台报键重复错误，可以稍微美化一下控制台信息，push判断一下键？？？（这个可改可不改）。
14.	整体PC端看上去有点空吗？大佬可以弄一下背景动画效果？？

[pixivicPC端正式问题.pdf](https://github.com/cheer-fun/pixivic-pc/files/4349251/pixivicPC.pdf)

**Comment by hyperMoss** [comment]
pixivic PC端正式问题
1.	用户中心登录后，样式变形。建议用户中心后期优化，可设头像，可改名称。（开发中
2.	排行搜索妹子图片很可爱，但是太隐蔽了，不移动到图片上不知道还有这个排行功能。（更换图标
 3.	尚未完成的功能？消息，个人中心，推荐画师，我的收藏点击都无效。（开发中
4.	搜索排行中的综合排行，女性，男性画作为空应该显示没有内容，然后不断在这两个切换的话偶尔会出现这个情况。(fixd,会提示无内容
5.	搜索排行中比如切到综合排行默认选择日为单位，切到漫画排行的时候也应该默认设置日为单位，不要默认为空，不然整个页面还是处于综合排行的页面。(fixd
6.	顶部的快速搜索中，切换漫画，插画，作者没有效果。（待查
7.	收藏图片失败，接口报错。fixd
8.	搜索作品输入为空时，页面一片空白，可以设置默认展示图片（已设置输入空格，空白不跳转
9.	画作详情页面中画师其他的画作以及头像展示问题（找后端
10.	画师添加关注失败（开发中
11.	找后端
12.	看不懂，详细点
13.	没什么必要改，vue route自带的错误
14.	后期按文档优化
