### ISSUE TITLE
瀑布流页面出现应该被过滤掉的图

### ISSUE THREAD

**Issue by OysterQAQ** [cheer-fun/pixivic-pc#38]
bug在改变窗口大小后复现，比如f12，应当从接口层面过滤
![image](https://user-images.githubusercontent.com/31726597/93011956-481ab780-f5ce-11ea-8ffd-b1081f5632a0.png)
![image](https://user-images.githubusercontent.com/31726597/93011960-4fda5c00-f5ce-11ea-87c7-ba89bc91dd2f.png)

**Comment by hyperMoss** [comment]
fixd
