### ISSUE TITLE
关于页面渲染的问题？

### ISSUE THREAD

**Issue by sakuracg** [cheer-fun/pixivic-pc#4]
想问一下，前端vue后端java，那么页面渲染问题是怎么处理的， 我看了一下vue的PC端源码，也没有服务端渲染的代码？想知道一下怎么处理SEO和服务器端渲染的。

**Comment by sakuracg** [comment]
在此，先谢谢答复呐~

**Comment by hyperMoss** [comment]
没有采用ssr，就前端打包出来，挂载为后端静态资源，至于seo，这个主站之前就有搜索排名，目前是使用的meta标签，进行seo优化。

**Comment by sakuracg** [comment]
懂了，谢谢
