### ISSUE TITLE
左侧导航栏直接用的margin,导致不必要的页面滚动条,影响交互体验

### ISSUE THREAD

**Issue by Kur1ko** [cheer-fun/pixivic-pc#5]
考虑局部用flex布局吧.
LeftSide.vue文件,
`
.LeftSide {
  height:100%;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  justify-content:  space-between;
  align-content: center;
  .beian{
    width: 15px;
    // margin: 400px auto 0;
    line-height: 24px;
    font-size: 12px;
    word-wrap: break-word;/*英文的时候需要加上这句，自动换行*/
    word-break:break-all;
  }
}
`
另外a标签套div里吧.

**Comment by hyperMoss** [comment]
okok,谢谢大佬指出错误
